### PR TITLE
Fix issues

### PR DESCRIPTION
**Pull request by TimL20**
This should fix the following issues (not tested though):
- Gnome keymap (#21 )
- Disable GNOME/GDM sleep (#22 )
- Enable appindicator (#19 )
- Wallpaper set (#20)

Not so sure with the last one, I haven't really changed much. But it should work.

### CODE REVIEW

**Comment by TimL20** [comment]
Also just added sing a auto (DHCP) connection after reboot and deleting the temporary one

**Comment by frankenstein91** [comment]
#22 not fixed

**Comment by frankenstein91** [comment]
#21 not fixed

**Comment by frankenstein91** [comment]
#20 is working now

**Comment by frankenstein91** [comment]
#19 is fixed and activ

**Comment by frankenstein91** [comment]
grafik
unfortunately I cannot copy from my VM. But the error with the standby is actually already solved #22. but we should perhaps clarify this more precisely and set this value to 0.

**Comment by frankenstein91** [comment]
the value #21
grafik

**Comment by TimL20** [comment]
I made an attempt to fix the remaining issues.

Also Added fix for linter syntax error (that came up while syntax actually was correct).

**Pull request merged**
